//
// Created by TTHOMAS on 5/8/2018.
//
#include <jni.h>

#ifndef CONTACTSAPP_CONTACTSDKJNI_H
#define CONTACTSAPP_CONTACTSDKJNI_H

/* DO NOT EDIT THIS FILE - it is machine generated */

enum {
    FAILURE = 0,
    SUCCESS = 1
};

/* Header for class contactSdkClass */


#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     contactSdkClass
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pthomasdesigns_libcontactandroid_NativeInterfaceImpl_nativeInitInternal
        (JNIEnv *, jclass, jobject);

/*
 * Class:     contactSdkClass
 * Method:    nativeShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pthomasdesigns_libcontactandroid_NativeInterfaceImpl_nativeShutdownInternal
        (JNIEnv *, jclass);


/*
 * Class:     contactSdkClass
 * Method:    addContact
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/pthomasdesigns/libcontactandroid/ContactSdk/AddContactListener;)V
 */
JNIEXPORT jint JNICALL Java_com_pthomasdesigns_libcontactandroid_NativeInterfaceImpl_addContactInternal
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     contactSdkClass
 * Method:    getAllContacts
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_pthomasdesigns_libcontactandroid_NativeInterfaceImpl_getAllContactsInternal
        (JNIEnv *, jclass);

/*
 * Class:     contactSdkClass
 * Method:    setUpdateContactListenerInternal
 * Signature: (Lcom/pthomasdesigns/libcontactandroid/ContactSdk/UpdateContactListener;)V
 */
JNIEXPORT void JNICALL Java_com_pthomasdesigns_libcontactandroid_NativeInterfaceImpl_setUpdateContactListenerInternal
        (JNIEnv *, jclass, jobject);


#ifdef __cplusplus
}
#endif

#endif //CONTACTSAPP_CONTACTSDKJNI_H
